# Generated by Django 5.1.4 on 2024-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_userquizscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz", name="description", field=models.TextField(null=True),
        ),
    ]
